FROM python:3.9-alpine3.15

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN apk update && \
    apk upgrade && \
    apk add docker && \
    apk add bash && \
    apk add git && \
    pip install awscli

COPY . .
